### ISSUE TITLE
Infinite loading for a username if it does not exist.

### ISSUE THREAD

**Issue by ameybh** [vansh-tiwari/trashtalk#6]
Reproduction steps:
1. Go to [Trashtalk](http://vanshtiwari.me/trashtalk.html)
2. Enter username1 as "vanshtiwari999", which does not exist, username2 as "vanshtiwari" or vice-versa.
3. The data for the username that does not exist will keep on loading. (Although, there is a "Refresh" message, it's not clear what to do).

**Comment by vansh-tiwari** [comment]
Fixed
